// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxrlWlMRomwMemNoh8ONnJ5PmdzPT5yPA',
    appId: '1:808141670120:web:89244d1be4228043b12b5d',
    messagingSenderId: '808141670120',
    projectId: 'cargocontrol-d5ef8',
    authDomain: 'cargocontrol-d5ef8.firebaseapp.com',
    storageBucket: 'cargocontrol-d5ef8.appspot.com',
    measurementId: 'G-CQ1ZLNMLJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK7ye_RbicvDNy2qQdmtPOJWBQhxyxm2U',
    appId: '1:808141670120:android:6d6a9c4cb2924203b12b5d',
    messagingSenderId: '808141670120',
    projectId: 'cargocontrol-d5ef8',
    storageBucket: 'cargocontrol-d5ef8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwapjbaYMkCqKS0XeZYD4kfIQ2J8PJ0Y8',
    appId: '1:808141670120:ios:80327f943b1cce41b12b5d',
    messagingSenderId: '808141670120',
    projectId: 'cargocontrol-d5ef8',
    storageBucket: 'cargocontrol-d5ef8.appspot.com',
    iosClientId: '808141670120-3ptpg1j2s9n5dvdak44gnskvpbjudnbd.apps.googleusercontent.com',
    iosBundleId: 'com.example.cargocontrol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwapjbaYMkCqKS0XeZYD4kfIQ2J8PJ0Y8',
    appId: '1:808141670120:ios:80327f943b1cce41b12b5d',
    messagingSenderId: '808141670120',
    projectId: 'cargocontrol-d5ef8',
    storageBucket: 'cargocontrol-d5ef8.appspot.com',
    iosClientId: '808141670120-3ptpg1j2s9n5dvdak44gnskvpbjudnbd.apps.googleusercontent.com',
    iosBundleId: 'com.example.cargocontrol',
  );
}
